version: '3'
services:
  vpnonline:
    build:
      dockerfile: Dockerfile
      context: .
    image: vpnonline
    container_name: vpnonline
    volumes:
      - .:/usr/local/app
    restart: always
    ports:
      - '7788:5000'       