name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
    
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker build and push
        uses:  docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            debmaiia/vpnonline:latest
            debmaiia/vpnonline:${{ github.run_number}}
            